version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      soroban-sdk:
        patterns:
          - "soroban-sdk"
          - "soroban-*"

  - package-ecosystem: "npm"
    directory: "/bindings/attester-registry"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/bindings/attestation-registry"
    schedule:
      interval: "weekly"
