version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      soroban-sdk:
        patterns:
          - "soroban-sdk"
          - "soroban-*"
