#!/usr/bin/env python3
"""Generate (or check) `packages/events/src/generated.ts`, the typed event
decoder table for `@lafiya/events`, from the committed interface snapshots.

    python3 scripts/conformance/gen_events_ts.py            # write generated.ts
    python3 scripts/conformance/gen_events_ts.py --check     # diff, don't write

The snapshots in `snapshots/` are themselves checked against the built Wasm
by `check_snapshot.py`, so a new or changed `#[contractevent]` that lands
without regenerating the snapshot *and* this file fails CI. Reading the
snapshots (rather than the Wasm) lets the drift check run without the
`stellar` CLI or a contract build.

Contracts in `contracts.py` with no `event_v0` entries (e.g. the multisig
account today) contribute no decoders; adding events to them only needs a
snapshot entry in `contracts.py`.
"""
import json
import sys

from contracts import CONTRACTS, REPO_ROOT, SNAPSHOT_DIR

OUT = REPO_ROOT / "packages" / "events" / "src" / "generated.ts"

HEADER = """// Generated by scripts/conformance/gen_events_ts.py -- do not hand-edit.
// Regenerate with `python3 scripts/conformance/gen_events_ts.py`.

import type { EventSpec } from "./spec.js";
"""

_TS_SCALARS = {
    "address": "string",
    "bool": "boolean",
    "bytes": "string",
    "i32": "number",
    "u32": "number",
    "i64": "bigint",
    "u64": "bigint",
    "i128": "bigint",
    "u128": "bigint",
    "i256": "bigint",
    "u256": "bigint",
    "timepoint": "bigint",
    "duration": "bigint",
    "string": "string",
    "symbol": "string",
    "void": "null",
}


def ts_type(t):
    if isinstance(t, str):
        return _TS_SCALARS.get(t, "unknown")
    ((kind, body),) = t.items()
    if kind == "bytes_n":
        return "string"
    if kind == "option":
        return f"{ts_type(body['value_type'])} | undefined"
    if kind == "vec":
        return f"Array<{ts_type(body['element_type'])}>"
    return "unknown"


def camel(name):
    head, *rest = name.split("_")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def load_events():
    """{event name: [(contract, spec), ...]} across every contract."""
    events = {}
    for contract in sorted(CONTRACTS):
        path = SNAPSHOT_DIR / f"{contract}.json"
        if not path.exists():
            continue
        for entry in json.loads(path.read_text()):
            if entry["kind"] == "event_v0":
                events.setdefault(entry["spec"]["name"], []).append((contract, entry["spec"]))
    return events


def spec_literal(spec):
    fields = [
        {
            "name": p["name"],
            "key": camel(p["name"]),
            "type": p["type_"],
            "location": "topic" if p["location"] == "topic_list" else "data",
        }
        for p in spec["params"]
    ]
    return json.dumps(
        {
            "prefixTopics": spec["prefix_topics"],
            "dataFormat": spec["data_format"],
            "fields": fields,
        },
        sort_keys=True,
    )


def render():
    events = load_events()
    out = [HEADER]

    kinds = sorted(events)
    out.append("/** Every event kind emitted by a Lafiya contract. */")
    out.append("export type EventKind =")
    out.append("\n".join(f'  | "{k}"' for k in kinds) + ";\n")

    for kind in kinds:
        specs = events[kind]
        # Same-named events must agree across contracts to share one type.
        distinct = {spec_literal(s) for _, s in specs}
        if len(distinct) != 1:
            sys.exit(f"error: event {kind} has different shapes across contracts")
        _, spec = specs[0]
        out.append(f"export interface {kind}Payload {{")
        for p in spec["params"]:
            out.append(f"  {camel(p['name'])}: {ts_type(p['type_'])};")
        out.append("}\n")

    out.append("/** Decoded payload type for each event kind. */")
    out.append("export interface EventPayloads {")
    for kind in kinds:
        out.append(f"  {kind}: {kind}Payload;")
    out.append("}\n")

    out.append("/**")
    out.append(" * Payload versions per event kind, newest first. A decoder tries each in")
    out.append(" * order, so an event that gains a field keeps decoding historical payloads")
    out.append(" * once the old shape is kept here under the event-versioning convention.")
    out.append(" */")
    out.append("export const EVENT_SPECS: Record<EventKind, readonly EventSpec[]> = {")
    for kind in kinds:
        out.append(f"  {kind}: [{spec_literal(events[kind][0][1])}],")
    out.append("};\n")

    out.append("/** Contracts that emit each event kind. */")
    out.append("export const EVENT_CONTRACTS: Record<EventKind, readonly string[]> = {")
    for kind in kinds:
        names = json.dumps(sorted({c for c, _ in events[kind]}))
        out.append(f"  {kind}: {names},")
    out.append("};")
    return "\n".join(out) + "\n"


def main():
    rendered = render()
    if "--check" in sys.argv[1:]:
        if not OUT.exists() or OUT.read_text() != rendered:
            print(f"[events-ts] {OUT} is stale -- run `python3 scripts/conformance/gen_events_ts.py`")
            sys.exit(1)
        print(f"[events-ts] OK -- {OUT.name} matches the interface snapshots")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    print(f"[events-ts] wrote {OUT}")


if __name__ == "__main__":
    main()
