// Generated by scripts/conformance/gen_events_ts.py -- do not hand-edit.
// Regenerate with `python3 scripts/conformance/gen_events_ts.py`.

import type { EventSpec } from "./spec.js";

/** Every event kind emitted by a Lafiya contract. */
export type EventKind =
  | "AdminTransferred"
  | "AttestationRecorded"
  | "AttestationRevoked"
  | "AttesterAdded"
  | "AttesterInfoUpdated"
  | "AttesterRegistryRepointed"
  | "AttesterReinstated"
  | "AttesterRemoved"
  | "AttesterSuspended"
  | "Initialized"
  | "Paused"
  | "Unpaused"
  | "Upgraded";

export interface AdminTransferredPayload {
  previousAdmin: string;
  newAdmin: string;
}

export interface AttestationRecordedPayload {
  recordHash: string;
  attester: string;
  timestamp: bigint;
}

export interface AttestationRevokedPayload {
  recordHash: string;
}

export interface AttesterAddedPayload {
  attester: string;
}

export interface AttesterInfoUpdatedPayload {
  attester: string;
}

export interface AttesterRegistryRepointedPayload {
  previous: string;
  new: string;
}

export interface AttesterReinstatedPayload {
  attester: string;
}

export interface AttesterRemovedPayload {
  attester: string;
}

export interface AttesterSuspendedPayload {
  attester: string;
}

export interface InitializedPayload {
  admin: string;
}

export interface PausedPayload {
  by: string;
}

export interface UnpausedPayload {
  by: string;
}

export interface UpgradedPayload {
  newWasmHash: string;
}

/** Decoded payload type for each event kind. */
export interface EventPayloads {
  AdminTransferred: AdminTransferredPayload;
  AttestationRecorded: AttestationRecordedPayload;
  AttestationRevoked: AttestationRevokedPayload;
  AttesterAdded: AttesterAddedPayload;
  AttesterInfoUpdated: AttesterInfoUpdatedPayload;
  AttesterRegistryRepointed: AttesterRegistryRepointedPayload;
  AttesterReinstated: AttesterReinstatedPayload;
  AttesterRemoved: AttesterRemovedPayload;
  AttesterSuspended: AttesterSuspendedPayload;
  Initialized: InitializedPayload;
  Paused: PausedPayload;
  Unpaused: UnpausedPayload;
  Upgraded: UpgradedPayload;
}

/**
 * Payload versions per event kind, newest first. A decoder tries each in
 * order, so an event that gains a field keeps decoding historical payloads
 * once the old shape is kept here under the event-versioning convention.
 */
export const EVENT_SPECS: Record<EventKind, readonly EventSpec[]> = {
  AdminTransferred: [{"dataFormat": "map", "fields": [{"key": "previousAdmin", "location": "topic", "name": "previous_admin", "type": "address"}, {"key": "newAdmin", "location": "topic", "name": "new_admin", "type": "address"}], "prefixTopics": ["admin_transferred"]}],
  AttestationRecorded: [{"dataFormat": "map", "fields": [{"key": "recordHash", "location": "topic", "name": "record_hash", "type": {"bytes_n": {"n": 32}}}, {"key": "attester", "location": "data", "name": "attester", "type": "address"}, {"key": "timestamp", "location": "data", "name": "timestamp", "type": "u64"}], "prefixTopics": ["attestation_recorded"]}],
  AttestationRevoked: [{"dataFormat": "map", "fields": [{"key": "recordHash", "location": "topic", "name": "record_hash", "type": {"bytes_n": {"n": 32}}}], "prefixTopics": ["attestation_revoked"]}],
  AttesterAdded: [{"dataFormat": "map", "fields": [{"key": "attester", "location": "topic", "name": "attester", "type": "address"}], "prefixTopics": ["attester_added"]}],
  AttesterInfoUpdated: [{"dataFormat": "map", "fields": [{"key": "attester", "location": "topic", "name": "attester", "type": "address"}], "prefixTopics": ["attester_info_updated"]}],
  AttesterRegistryRepointed: [{"dataFormat": "map", "fields": [{"key": "previous", "location": "topic", "name": "previous", "type": "address"}, {"key": "new", "location": "topic", "name": "new", "type": "address"}], "prefixTopics": ["attester_registry_repointed"]}],
  AttesterReinstated: [{"dataFormat": "map", "fields": [{"key": "attester", "location": "topic", "name": "attester", "type": "address"}], "prefixTopics": ["attester_reinstated"]}],
  AttesterRemoved: [{"dataFormat": "map", "fields": [{"key": "attester", "location": "topic", "name": "attester", "type": "address"}], "prefixTopics": ["attester_removed"]}],
  AttesterSuspended: [{"dataFormat": "map", "fields": [{"key": "attester", "location": "topic", "name": "attester", "type": "address"}], "prefixTopics": ["attester_suspended"]}],
  Initialized: [{"dataFormat": "map", "fields": [{"key": "admin", "location": "topic", "name": "admin", "type": "address"}], "prefixTopics": ["initialized"]}],
  Paused: [{"dataFormat": "map", "fields": [{"key": "by", "location": "topic", "name": "by", "type": "address"}], "prefixTopics": ["paused"]}],
  Unpaused: [{"dataFormat": "map", "fields": [{"key": "by", "location": "topic", "name": "by", "type": "address"}], "prefixTopics": ["unpaused"]}],
  Upgraded: [{"dataFormat": "map", "fields": [{"key": "newWasmHash", "location": "topic", "name": "new_wasm_hash", "type": {"bytes_n": {"n": 32}}}], "prefixTopics": ["upgraded"]}],
};

/** Contracts that emit each event kind. */
export const EVENT_CONTRACTS: Record<EventKind, readonly string[]> = {
  AdminTransferred: ["attestation-registry", "attester-registry"],
  AttestationRecorded: ["attestation-registry"],
  AttestationRevoked: ["attestation-registry"],
  AttesterAdded: ["attester-registry"],
  AttesterInfoUpdated: ["attester-registry"],
  AttesterRegistryRepointed: ["attestation-registry"],
  AttesterReinstated: ["attester-registry"],
  AttesterRemoved: ["attester-registry"],
  AttesterSuspended: ["attester-registry"],
  Initialized: ["attester-registry"],
  Paused: ["attestation-registry", "attester-registry"],
  Unpaused: ["attestation-registry", "attester-registry"],
  Upgraded: ["attester-registry"],
};
