#!/usr/bin/env python3
"""Generate Lafiya's SEP-1 stellar.toml (docs/specs/stellar-toml.md) from repo state.

Inputs:
  config/networks.toml            deployed contract IDs per network
  config/stellar-toml.meta.toml   org metadata, signing key, manifest URL template
  --manifest PATH                 release manifest (scripts/generate_release_manifest.py)
                                  supplying wasm hashes for deployed contracts

A deployed contract's wasm hash comes from --manifest; without one it is carried
forward from the committed config/stellar.toml entry for the same contract ID,
so `--check` works in CI without rebuilding a release.

Usage:
    scripts/generate_stellar_toml.py [--manifest PATH] [-o PATH]
    scripts/generate_stellar_toml.py --check
"""
import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NETWORKS = ROOT / "config" / "networks.toml"
META = ROOT / "config" / "stellar-toml.meta.toml"
OUTPUT = ROOT / "config" / "stellar.toml"


def load_toml(path):
    with open(path, "rb") as f:
        return tomllib.load(f)


def q(value):
    """TOML basic string (JSON string escaping is valid TOML)."""
    return json.dumps(value, ensure_ascii=False)


def committed_entries(path):
    if not path.is_file():
        return {}
    return {
        (e["network"], e["name"], e["contract_id"]): e
        for e in load_toml(path).get("LAFIYA_CONTRACTS", [])
    }


def contract_entries(networks, meta, manifest, previous):
    hashes, manifest_url = {}, None
    if manifest:
        hashes = {
            c["name"].replace("-", "_"): c["wasm"]["sha256"] for c in manifest["contracts"]
        }
        manifest_url = meta["release_manifest_url"].format(
            version=manifest["release"]["workspace_version"]
        )

    entries, errors = [], []
    for network, cfg in sorted(networks.items()):
        for name, contract_id in sorted(cfg.get("contracts", {}).items()):
            if not contract_id:
                continue
            prev = previous.get((network, name, contract_id), {})
            wasm_hash = hashes.get(name) or prev.get("wasm_hash")
            if not wasm_hash:
                errors.append(
                    f"{network}.{name} ({contract_id}): no wasm hash -- pass --manifest "
                    "for the release this contract was deployed from"
                )
                continue
            entries.append(
                {
                    "name": name,
                    "network": network,
                    "network_passphrase": cfg["network_passphrase"],
                    "contract_id": contract_id,
                    "wasm_hash": wasm_hash,
                    "release_manifest": manifest_url or prev.get("release_manifest", ""),
                }
            )
    return entries, errors


def render(meta, entries):
    lines = [
        "# GENERATED by scripts/generate_stellar_toml.py -- do not edit by hand.",
        "# Spec: docs/specs/stellar-toml.md",
        f"# Served at https://{meta['domain']}/.well-known/stellar.toml",
        "",
    ]
    if meta.get("signing_key"):
        lines += [f"SIGNING_KEY = {q(meta['signing_key'])}", ""]
    lines.append("[DOCUMENTATION]")
    lines += [f"{k} = {q(v)}" for k, v in meta["documentation"].items()]
    for principal in meta.get("principals", []):
        lines += ["", "[[PRINCIPALS]]"]
        lines += [f"{k} = {q(v)}" for k, v in principal.items()]
    for entry in entries:
        lines += ["", "[[LAFIYA_CONTRACTS]]"]
        lines += [f"{k} = {q(v)}" for k, v in entry.items() if v]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--manifest", type=Path, help="release manifest JSON")
    parser.add_argument("-o", "--output", type=Path, default=OUTPUT)
    parser.add_argument(
        "--check", action="store_true", help="fail if the output file is out of date"
    )
    args = parser.parse_args()

    meta = load_toml(META)
    manifest = json.loads(args.manifest.read_text()) if args.manifest else None
    entries, errors = contract_entries(
        load_toml(NETWORKS), meta, manifest, committed_entries(args.output)
    )
    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
    rendered = render(meta, entries)

    if args.check:
        current = args.output.read_text() if args.output.is_file() else ""
        if current != rendered:
            print(
                f"{args.output} is out of date; run `make stellar-toml`",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"[stellar-toml] OK -- {args.output} matches repository state")
        return
    args.output.write_text(rendered)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
