//! `cargo xtask docs`: generate the contract and CLI reference pages of the
//! documentation site (`--check` fails if the committed pages have drifted),
//! then stage the mdBook source in `target/book-src`.
//!
//! Staging copies `docs/`, imports the Markdown files that live elsewhere in
//! the repository (`IMPORTS`), and rewrites links that leave the site to point
//! at GitHub, so authored docs keep working both on GitHub and in the site.

use anyhow::{bail, Context, Result};
use serde_json::Value;
use std::fmt::Write as _;
use std::path::Path;
use std::process::Command;

const CONTRACTS: [&str; 3] = [
    "attester-registry",
    "attestation-registry",
    "multisig-account",
];
const CONTRACT_DIR: &str = "docs/reference/contracts";
const CLI_DIR: &str = "docs/reference/cli";
const STAGE_DIR: &str = "target/book-src";
const REPO_URL: &str = "https://github.com/Lafiya-xyz/Lafiya-contract";
/// Markdown outside `docs/` rendered in the site: (repository path, site path).
const IMPORTS: [(&str, &str); 12] = [
    ("SECURITY.md", "imported/security.md"),
    ("sandbox/README.md", "imported/sandbox.md"),
    (
        "verification/tla/README.md",
        "imported/formal-verification.md",
    ),
    ("CONTRIBUTING.md", "imported/contributing.md"),
    ("PUBLISHING.md", "imported/publishing.md"),
    ("CHANGELOG.md", "imported/changelog.md"),
    ("config/README.md", "imported/config.md"),
    ("scripts/README.md", "imported/scripts.md"),
    (
        "crates/lafiya-commitment/README.md",
        "imported/lafiya-commitment.md",
    ),
    (
        "crates/lafiya-rpc-resilience/README.md",
        "imported/lafiya-rpc-resilience.md",
    ),
    (
        "bindings/attester-registry/README.md",
        "imported/bindings-attester-registry.md",
    ),
    (
        "bindings/attestation-registry/README.md",
        "imported/bindings-attestation-registry.md",
    ),
];
const HEADER: &str =
    "<!-- GENERATED by `cargo xtask docs`. Do not edit; edit the source and regenerate. -->\n\n";

pub fn run(check: bool) -> Result<()> {
    let mut pages = Vec::new();
    build_wasm()?;
    for c in CONTRACTS {
        let wasm = format!("target/wasm32v1-none/release/{}.wasm", c.replace('-', "_"));
        let bytes = std::fs::read(&wasm).with_context(|| format!("reading {wasm}"))?;
        let spec = soroban_spec::read::from_wasm(&bytes)
            .map_err(|e| anyhow::anyhow!("reading contract spec from {wasm}: {e}"))?;
        let spec = serde_json::to_value(&spec)?;
        pages.push((format!("{CONTRACT_DIR}/{c}.md"), contract_page(c, &spec)));
    }
    pages.push((
        format!("{CLI_DIR}/lafiya-cli.md"),
        cli_page("lafiya-cli", &["run", "-q", "-p", "lafiya-cli", "--"]),
    ));
    pages.push((
        format!("{CLI_DIR}/xtask.md"),
        cli_page("cargo xtask", &["run", "-q", "-p", "xtask", "--"]),
    ));

    let mut drifted = Vec::new();
    for (path, body) in &pages {
        let current = std::fs::read_to_string(path).unwrap_or_default();
        if current == *body {
            continue;
        }
        if check {
            drifted.push(path.as_str());
        } else {
            std::fs::create_dir_all(Path::new(path).parent().expect("has parent"))?;
            std::fs::write(path, body)?;
            println!("wrote {path}");
        }
    }
    if !drifted.is_empty() {
        bail!(
            "generated reference is out of date: {}\nrun `cargo xtask docs` and commit the result",
            drifted.join(", ")
        );
    }
    stage()?;
    println!("staged mdBook source in {STAGE_DIR}");
    Ok(())
}

fn build_wasm() -> Result<()> {
    let mut cmd = Command::new("cargo");
    cmd.args(["build", "--release", "--target", "wasm32v1-none"]);
    for c in CONTRACTS {
        cmd.args(["-p", c]);
    }
    if !cmd.status()?.success() {
        bail!("building contract wasm failed");
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Staging
// ---------------------------------------------------------------------------

fn stage() -> Result<()> {
    let _ = std::fs::remove_dir_all(STAGE_DIR);
    copy_dir(Path::new("docs"), Path::new(STAGE_DIR))?;
    // Book configuration and theme are read from docs/, not the source dir.
    std::fs::remove_file(Path::new(STAGE_DIR).join("book.toml"))?;
    std::fs::remove_dir_all(Path::new(STAGE_DIR).join("theme"))?;
    for (src, dest) in IMPORTS {
        let text = std::fs::read_to_string(src).with_context(|| format!("reading {src}"))?;
        let out = Path::new(STAGE_DIR).join(dest);
        std::fs::create_dir_all(out.parent().expect("has parent"))?;
        std::fs::write(out, rewrite_links(&text, src, dest))?;
    }
    Ok(())
}

fn copy_dir(from: &Path, to: &Path) -> Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let (src, dest) = (entry.path(), to.join(entry.file_name()));
        if entry.file_type()?.is_dir() {
            copy_dir(&src, &dest)?;
        } else if src.extension().is_some_and(|e| e == "md") {
            let text = std::fs::read_to_string(&src)?;
            let repo_path = src.to_string_lossy().replace('\\', "/");
            let site_path = repo_path.trim_start_matches("docs/").to_string();
            let mut text = rewrite_links(&text, &repo_path, &site_path);
            if site_path == "adr/README.md" {
                text = status_badges(&text);
            }
            std::fs::write(&dest, text)?;
        } else {
            std::fs::copy(&src, &dest)?;
        }
    }
    Ok(())
}

/// Render the Status column of the ADR index as badges.
fn status_badges(text: &str) -> String {
    text.lines()
        .map(|line| {
            let Some(cell) = line.strip_suffix(" |").and_then(|l| l.rsplit_once("| ")) else {
                return line.to_string();
            };
            let status = cell.1.trim();
            let class = status
                .split_whitespace()
                .next()
                .unwrap_or_default()
                .to_lowercase();
            if ["accepted", "proposed", "deprecated", "superseded"].contains(&class.as_str()) {
                format!(
                    "{}| <span class=\"adr-status {class}\">{status}</span> |",
                    cell.0
                )
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

/// Normalize `base_dir/target` into repository-relative components; `Err(n)`
/// if it climbs `n` levels above the repository root.
fn resolve(base_dir: &str, target: &str) -> std::result::Result<Vec<String>, usize> {
    let mut parts: Vec<String> = Vec::new();
    let mut above = 0;
    for c in base_dir.split('/').chain(target.split('/')) {
        match c {
            "" | "." => {}
            ".." => {
                if parts.pop().is_none() {
                    above += 1;
                }
            }
            c => parts.push(c.to_string()),
        }
    }
    if above > 0 {
        Err(above)
    } else {
        Ok(parts)
    }
}

fn dir_of(path: &str) -> &str {
    path.rsplit_once('/').map_or("", |(d, _)| d)
}

/// Relative link from the page at `from` to `to` (both site paths).
fn relative(from: &str, to: &str) -> String {
    let depth = dir_of(from).split('/').filter(|c| !c.is_empty()).count();
    "../".repeat(depth) + to
}

/// Where a link written in the file at `repo_path` should point once that
/// file is served at `site_path`.
fn rewrite_target(target: &str, repo_path: &str, site_path: &str) -> Option<String> {
    if target.is_empty()
        || target.starts_with('#')
        || target.contains("://")
        || target.starts_with("mailto:")
    {
        return None;
    }
    let (path, anchor) = target.split_once('#').map_or((target, ""), |(p, a)| (p, a));
    let anchor = if anchor.is_empty() {
        String::new()
    } else {
        format!("#{anchor}")
    };
    let parts = match resolve(dir_of(repo_path), path) {
        Ok(parts) => parts,
        Err(above) => {
            // Links such as `../../security/advisories/new` are relative to
            // the file's GitHub URL (`<repo>/blob/main/...`).
            let base = ["blob", "main"];
            let keep = base.len().checked_sub(above)?;
            let prefix = base[..keep].join("/");
            let rest = path.trim_start_matches("../").trim_start_matches("./");
            let url = [REPO_URL, &prefix, rest]
                .iter()
                .filter(|s| !s.is_empty())
                .copied()
                .collect::<Vec<_>>()
                .join("/");
            return Some(url + &anchor);
        }
    };
    let joined = parts.join("/");
    if let Some(inside) = joined.strip_prefix("docs/") {
        return Some(relative(site_path, inside) + &anchor);
    }
    if joined == "README.md" {
        return Some(relative(site_path, "overview.md") + &anchor);
    }
    if let Some((_, dest)) = IMPORTS.iter().find(|(src, _)| *src == joined) {
        return Some(relative(site_path, dest) + &anchor);
    }
    Some(format!("{REPO_URL}/blob/main/{joined}{anchor}"))
}

/// Rewrite every inline Markdown link target `](...)`, outside code fences.
fn rewrite_links(text: &str, repo_path: &str, site_path: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut in_fence = false;
    for line in text.split_inclusive('\n') {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
        }
        if in_fence {
            out.push_str(line);
            continue;
        }
        let mut rest = line;
        while let Some(i) = rest.find("](") {
            out.push_str(&rest[..i + 2]);
            rest = &rest[i + 2..];
            let Some(end) = rest.find(')') else { break };
            let target = &rest[..end];
            match rewrite_target(target, repo_path, site_path) {
                Some(t) => out.push_str(&t),
                None => out.push_str(target),
            }
            rest = &rest[end..];
        }
        out.push_str(rest);
    }
    out
}

// ---------------------------------------------------------------------------
// Contract reference (from the contract spec embedded in the Wasm)
// ---------------------------------------------------------------------------

fn doc(v: &Value) -> String {
    v["doc"].as_str().unwrap_or_default().replace("\\n", "\n")
}

fn ty(t: &Value) -> String {
    if let Some(s) = t.as_str() {
        return match s {
            "address" => "Address",
            "bool" => "bool",
            "void" => "()",
            "error" => "Error",
            "symbol" => "Symbol",
            "string" => "String",
            "bytes" => "Bytes",
            "u32" => "u32",
            "i32" => "i32",
            "u64" => "u64",
            "i64" => "i64",
            "u128" => "u128",
            "i128" => "i128",
            "timepoint" => "Timepoint",
            "duration" => "Duration",
            "val" => "Val",
            other => other,
        }
        .to_string();
    }
    let (kind, v) = t
        .as_object()
        .and_then(|o| o.iter().next())
        .expect("type is a string or single-key object");
    match kind.as_str() {
        "option" => format!("Option<{}>", ty(&v["value_type"])),
        "result" => format!("Result<{}, {}>", ty(&v["ok_type"]), ty(&v["error_type"])),
        "vec" => format!("Vec<{}>", ty(&v["element_type"])),
        "map" => format!("Map<{}, {}>", ty(&v["key_type"]), ty(&v["value_type"])),
        "bytes_n" => format!("BytesN<{}>", v["n"]),
        "udt" => v["name"].as_str().unwrap_or_default().to_string(),
        "tuple" => format!(
            "({})",
            v["value_types"]
                .as_array()
                .map(|a| a.iter().map(ty).collect::<Vec<_>>().join(", "))
                .unwrap_or_default()
        ),
        other => other.to_string(),
    }
}

fn cell(s: &str) -> String {
    s.replace('\n', " ").replace('|', "\\|")
}

fn contract_page(name: &str, spec: &Value) -> String {
    let entries = spec.as_array().cloned().unwrap_or_default();
    let of = |kind: &str| -> Vec<Value> {
        entries
            .iter()
            .filter_map(|e| e.get(kind).cloned())
            .collect()
    };
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "# `{name}`\n");
    let _ = writeln!(
        out,
        "Interface reference generated from the contract spec embedded in `{}.wasm`. \
         See the contract's hand-written docs for design context.\n",
        name.replace('-', "_")
    );

    let _ = writeln!(out, "## Functions\n");
    let mut fns = of("function_v0");
    fns.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));
    for f in &fns {
        let inputs: Vec<String> = f["inputs"]
            .as_array()
            .into_iter()
            .flatten()
            .map(|i| {
                format!(
                    "{}: {}",
                    i["name"].as_str().unwrap_or_default(),
                    ty(&i["type_"])
                )
            })
            .collect();
        let output = f["outputs"]
            .as_array()
            .and_then(|o| o.first())
            .map(|o| format!(" -> {}", ty(o)))
            .unwrap_or_default();
        let name = f["name"].as_str().unwrap_or_default();
        let _ = writeln!(out, "### `{name}`\n");
        let _ = writeln!(
            out,
            "```rust\nfn {name}({}){output}\n```\n",
            inputs.join(", ")
        );
        let d = doc(f);
        if !d.is_empty() {
            let _ = writeln!(out, "{d}\n");
        }
    }

    let structs = of("udt_struct_v0");
    if !structs.is_empty() {
        let _ = writeln!(out, "## Types\n");
        for s in &structs {
            let _ = writeln!(out, "### `{}`\n", s["name"].as_str().unwrap_or_default());
            let d = doc(s);
            if !d.is_empty() {
                let _ = writeln!(out, "{d}\n");
            }
            let _ = writeln!(out, "| Field | Type | Description |\n| --- | --- | --- |");
            for f in s["fields"].as_array().into_iter().flatten() {
                let _ = writeln!(
                    out,
                    "| `{}` | `{}` | {} |",
                    f["name"].as_str().unwrap_or_default(),
                    ty(&f["type_"]),
                    cell(&doc(f))
                );
            }
            out.push('\n');
        }
    }

    for e in of("udt_error_enum_v0") {
        let _ = writeln!(
            out,
            "## Errors (`{}`)\n",
            e["name"].as_str().unwrap_or_default()
        );
        let _ = writeln!(out, "| Code | Name | Description |\n| --- | --- | --- |");
        for c in e["cases"].as_array().into_iter().flatten() {
            let _ = writeln!(
                out,
                "| {} | `{}` | {} |",
                c["value"],
                c["name"].as_str().unwrap_or_default(),
                cell(&doc(c))
            );
        }
        out.push('\n');
    }

    let mut events = of("event_v0");
    if !events.is_empty() {
        events.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));
        let _ = writeln!(out, "## Events\n");
        let _ = writeln!(
            out,
            "| Event | Topics | Data | Description |\n| --- | --- | --- | --- |"
        );
        for e in &events {
            let mut topics: Vec<String> = e["prefix_topics"]
                .as_array()
                .into_iter()
                .flatten()
                .map(|t| format!("`\"{}\"`", t.as_str().unwrap_or_default()))
                .collect();
            let mut data = Vec::new();
            for p in e["params"].as_array().into_iter().flatten() {
                let field = format!(
                    "`{}: {}`",
                    p["name"].as_str().unwrap_or_default(),
                    ty(&p["type_"])
                );
                if p["location"] == "topic_list" {
                    topics.push(field);
                } else {
                    data.push(field);
                }
            }
            let _ = writeln!(
                out,
                "| `{}` | {} | {} | {} |",
                e["name"].as_str().unwrap_or_default(),
                topics.join(", "),
                data.join(", "),
                cell(&doc(e))
            );
        }
        out.push('\n');
    }
    out.trim_end().to_string() + "\n"
}

// ---------------------------------------------------------------------------
// CLI reference (from clap's --help output)
// ---------------------------------------------------------------------------

fn help(cargo_args: &[&str], path: &[String]) -> Result<String> {
    let out = Command::new("cargo")
        .args(cargo_args)
        .args(path)
        .arg("--help")
        .output()?;
    if !out.status.success() {
        bail!("{}", String::from_utf8_lossy(&out.stderr).trim());
    }
    Ok(String::from_utf8_lossy(&out.stdout).trim_end().to_string())
}

/// Subcommand names listed under clap's "Commands:" heading.
fn subcommands(help: &str) -> Vec<String> {
    help.lines()
        .skip_while(|l| !l.starts_with("Commands:"))
        .skip(1)
        .take_while(|l| l.starts_with("  "))
        .filter_map(|l| l.split_whitespace().next())
        .filter(|c| *c != "help")
        .map(str::to_string)
        .collect()
}

fn cli_page(display: &str, cargo_args: &[&str]) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(out, "# `{display}`\n");
    let mut queue = vec![Vec::<String>::new()];
    while let Some(path) = queue.pop() {
        let text = match help(cargo_args, &path) {
            Ok(t) => t,
            Err(_) => {
                // Keep the site building while the binary doesn't compile; the
                // notice changes (and --check fails) as soon as it builds again.
                eprintln!("warning: `{display}` did not build; its reference is a placeholder");
                let _ = writeln!(
                    out,
                    "> **Not generated:** `{display}` did not build when this page was \
                     generated. Fix the build and rerun `cargo xtask docs`."
                );
                return out;
            }
        };
        let title = if path.is_empty() {
            display.to_string()
        } else {
            format!("{display} {}", path.join(" "))
        };
        if !path.is_empty() {
            let _ = writeln!(out, "## `{title}`\n");
        }
        let _ = writeln!(out, "```text\n{text}\n```\n");
        for sub in subcommands(&text).into_iter().rev() {
            let mut p = path.clone();
            p.push(sub);
            queue.push(p);
        }
    }
    out.trim_end().to_string() + "\n"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_nested_types() {
        let t: Value = serde_json::json!({"result": {"ok_type": {"option": {"value_type": {"udt": {"name": "Attestation"}}}}, "error_type": "error"}});
        assert_eq!(ty(&t), "Result<Option<Attestation>, Error>");
        assert_eq!(ty(&serde_json::json!({"bytes_n": {"n": 32}})), "BytesN<32>");
    }

    #[test]
    fn rewrites_links_leaving_the_site() {
        let r = |t, repo, site| rewrite_target(t, repo, site).unwrap();
        assert_eq!(
            r(
                "../../contracts/a/src/lib.rs#L1",
                "docs/adr/x.md",
                "adr/x.md"
            ),
            "https://github.com/Lafiya-xyz/Lafiya-contract/blob/main/contracts/a/src/lib.rs#L1"
        );
        assert_eq!(
            r("../glossary.md", "docs/adr/x.md", "adr/x.md"),
            "../glossary.md"
        );
        assert_eq!(
            r("../../PUBLISHING.md", "docs/adr/x.md", "adr/x.md"),
            "../imported/publishing.md"
        );
        assert_eq!(
            r(
                "README.md#getting-started",
                "CONTRIBUTING.md",
                "imported/contributing.md"
            ),
            "../overview.md#getting-started"
        );
        assert_eq!(
            r(
                "docs/releasing.md",
                "CONTRIBUTING.md",
                "imported/contributing.md"
            ),
            "../releasing.md"
        );
        assert_eq!(
            r(
                "../../security/advisories/new",
                "SECURITY.md",
                "imported/security.md"
            ),
            "https://github.com/Lafiya-xyz/Lafiya-contract/security/advisories/new"
        );
        assert_eq!(rewrite_target("#x", "a.md", "a.md"), None);
        assert_eq!(rewrite_target("https://x.org", "a.md", "a.md"), None);
    }

    #[test]
    fn leaves_code_fences_alone() {
        let text = "```\n[a](../../x)\n```\n[b](../../y)\n";
        let out = rewrite_links(text, "docs/adr/z.md", "adr/z.md");
        assert!(out.contains("[a](../../x)"));
        assert!(out.contains("[b](https://github.com/Lafiya-xyz/Lafiya-contract/blob/main/y)"));
    }

    #[test]
    fn finds_subcommands() {
        let h = "About\n\nUsage: x <COMMAND>\n\nCommands:\n  up    Start\n  down  Stop\n  help  Print\n\nOptions:\n  -h";
        assert_eq!(subcommands(h), vec!["up", "down"]);
    }
}
